server:
  port: 9010
spring:
  application:
    name: alpaca-blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/alpaca_blog?charset=utf8mb4&serverTimezone=GMT&useSSL=false&autoReconnect=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    serialization:
      indent-output: true
  redis:
    host: 127.0.0.1
    port: 6380
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
